server:
  port: 1234   #服务启动端口
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    max-connections: 20000

spring:
  mvc:
    static-path-pattern: /**
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/  #指向静态资源
  jackson:
    #设置空如何序列化
    defaultPropertyInclusion: ALWAYS
  datasource:
    name: oracle_con
    type: com.alibaba.druid.pool.DruidDataSource
    #druid相关配置
    druid:
      #监控统计拦截的filters
      filters: stat
      driver-class-name: com.mysql.cj.jdbc.Driver
      #基本属性
      url: jdbc:mysql://localhost:3306/sakila?serverTimezone=GMT%2B8
      username: root
      password: 123456
      #配置初始化大小/最小/最大
      initial-size: 1
      min-idle: 1
      max-active: 100
      #获取连接等待超时时间
      max-wait: 60000
      #间隔多久进行一次检测，检测需要关闭的空闲连接
      time-between-eviction-runs-millis: 60000
      #一个连接在池中最小生存的时间
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT * FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      #打开PSCache，并指定每个连接上PSCache的大小。oracle设为true，mysql设为false。分库分表较多推荐设置为false
      pool-prepared-statements: false
      max-pool-prepared-statement-per-connection-size: 20

#mybatis
mybatis:
  mapper-locations: classpath*:com/sakila/demo/mapper/*.xml     #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: com.sakila.demo.po    #注意：对应实体类的路径
  configuration:
    call-setters-on-nulls: true
    jdbc-type-for-null: 'null'

#pagehelper
pagehelper:
  helperDialect: oracle
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
  returnPageInfo: check